#include QMK_KEYBOARD_H
#include "keymap_bepo.h" 

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


 // Tap Dance declarations
enum {
   
    CH01,
    CH02,
    CH10,
    CH12,
    CH20,
    CH21

};

// Tap Dance definitions
tap_dance_action_t tap_dance_actions[] = {
   
// couche 0
    [CH01] = ACTION_TAP_DANCE_LAYER_MOVE(KC_P1,1),
    [CH02] = ACTION_TAP_DANCE_LAYER_MOVE(KC_P2,2),
// couche 1
    [CH10] = ACTION_TAP_DANCE_LAYER_MOVE(KC_NO,0), // remplacé par TG(0)
    [CH12] = ACTION_TAP_DANCE_LAYER_MOVE(KC_NO,2),
// couche 2
    [CH20] = ACTION_TAP_DANCE_LAYER_MOVE(KC_NO,0),
    [CH21] = ACTION_TAP_DANCE_LAYER_MOVE(KC_NO,1)

};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ortho_4x4(KC_PMNS, KC_P7, KC_P8, KC_P9, KC_PPLS, KC_P4, KC_P5, KC_P6, KC_PAST, TD(CH01), TD(CH02), KC_P3, KC_PSLS, KC_P0, BP_COMM,KC_PENT),
	[1] = LAYOUT_ortho_4x4(KC_VOLD, KC_CALC, KC_MAIL, KC_NUM, KC_VOLU, KC_WREF, KC_WBAK, KC_WFWD, KC_MUTE, KC_NO, TD(CH12), KC_NO, KC_PWR, TD(CH10) ,KC_SLEP, KC_WAKE),
	[2] = LAYOUT_ortho_4x4(KC_NO, BP_R, BP_M, BP_Q, KC_NO , BP_O, BP_H, BP_P, KC_NO, TD(CH21), KC_NO, KC_NO, KC_NO, TD(CH20), KC_NO, KC_NO)
};

